# server port
server:
  port: 8080

# database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://pnpweb.iptime.org:3306/realestate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dongil
    password: Isp0182292695@

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

